apiVersion: apps/v1
kind: Deployment
metadata:
  name: yw-test-12
  labels:
    app: yw-test-12
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1734385709530
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yw-test-12
  template:
    metadata:
      labels:
        app: yw-test-12
    spec:
      containers:
        - name: yw-test-12
          image: wyregistry.azurecr.io/image-workflow-1734385709530:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
