apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccc
  labels:
    app: ccc
  namespace: namespace-workflow-1681325139927
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccc
  template:
    metadata:
      labels:
        app: ccc
    spec:
      containers:
        - name: ccc
          image: acrworkflow1681325139927.azurecr.io/image-workflow-1681325139927:latest
          ports:
            - containerPort: 80