apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbbb
  labels:
    app: bbbb
  namespace: namespace-workflow-1681324559950
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbbb
  template:
    metadata:
      labels:
        app: bbbb
    spec:
      containers:
        - name: bbbb
          image: acrworkflow1681324559950.azurecr.io/image-workflow-1681324559950:latest
          ports:
            - containerPort: 80