apiVersion: v1
kind: Service
metadata:
  name: ccc
  namespace: namespace-workflow-1681325139927
spec:
  type: LoadBalancer
  selector:
    app: ccc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80