apiVersion: v1
kind: Service
metadata:
  name: bbbb
  namespace: namespace-workflow-1681324559950
spec:
  type: LoadBalancer
  selector:
    app: bbbb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80